name: Build Btrfs for Android 12 (5.10.136)

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:  # 允许手动触发

jobs:
  build:
    runs-on: ubuntu-22.04
    timeout-minutes: 60

    steps:
      # 1. 检出空仓库（仅占位）
      - name: Checkout
        uses: actions/checkout@v4  # 使用最新稳定版

      # 2. 安装依赖
      - name: Install Dependencies
        run: |
          sudo apt-get update -y
          sudo apt-get install -y git-core gnupg flex bison build-essential \
            zip curl zlib1g-dev gcc-multilib g++-multilib libc6-dev-i386 \
            libncurses5 lib32ncurses5-dev x11proto-core-dev libx11-dev \
            lib32z1-dev libgl1-mesa-dev libxml2-utils xsltproc unzip \
            fontconfig python3 bc cpio rsync kmod libelf-dev clang lld \
            git-lfs

      # 3. 下载 Android 12 的 5.10.136 内核源码
      - name: Clone Android Kernel
        run: |
          mkdir android-kernel && cd android-kernel
          repo init -u https://android.googlesource.com/kernel/manifest \
            -b android12-5.10 --depth=1
          repo sync -c -j$(nproc) --no-tags --no-clone-bundle
          cd common
          git checkout android12-5.10.136  # 精确版本

      # 4. 配置内核（启用Btrfs）
      - name: Configure Kernel
        run: |
          cd android-kernel/common
          make ARCH=arm64 gki_defconfig
          ./scripts/config --module CONFIG_BTRFS_FS
          ./scripts/config --disable MODULE_SIG  # 关闭签名验证（测试用）
          make ARCH=arm64 olddefconfig

      # 5. 编译 Btrfs 模块
      - name: Build Btrfs Module
        run: |
          cd android-kernel/common
          make ARCH=arm64 CROSS_COMPILE=aarch64-linux-gnu- \
            -j$(nproc) fs/btrfs/btrfs.ko

      # 6. 上传编译好的模块（使用固定版本v3.1.2）
      - name: Upload Artifact
        uses: actions/upload-artifact@v3.1.2  # 明确指定版本
        with:
          name: btrfs.ko-android12-5.10.136
          path: android-kernel/common/fs/btrfs/btrfs.ko
