- name: Find and Checkout Correct Tag
  run: |
    cd android-kernel/common
    
    # 设置超时和重试机制
    timeout 120 git fetch --tags || {
      echo "::warning::git fetch --tags timed out, continuing with local tags"
    }
    
    echo "Available tags for Android 12 5.10.136:"
    git tag -l "*5.10*" | sort -V | tee available_tags.txt
    
    # 自动选择最接近的tag或回退到分支
    SELECTED_TAG=$(
      grep -E "5\.10\.136" available_tags.txt | head -1 || 
      grep -E "5\.10" available_tags.txt | head -1
    )
    
    if [ -z "$SELECTED_TAG" ]; then
      echo "::warning::No matching tag found, falling back to branch"
      git checkout common-android12-5.10
    else
      echo "Selected tag: $SELECTED_TAG"
      git checkout "$SELECTED_TAG"
    fi
    
    # 验证当前版本
    echo "Current HEAD:"
    git log -1 --oneline
    echo "Kernel version:"
    grep -E "VERSION|PATCHLEVEL|SUBLEVEL" Makefile
