name: Build Btrfs for Android 12 (5.10.136)

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-22.04
    timeout-minutes: 60

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Dependencies
        run: |
          sudo apt-get update -y
          sudo apt-get install -y git-core gnupg flex bison build-essential \
            zip curl zlib1g-dev gcc-multilib g++-multilib libc6-dev-i386 \
            libncurses5 lib32ncurses5-dev x11proto-core-dev libx11-dev \
            lib32z1-dev libgl1-mesa-dev libxml2-utils xsltproc unzip \
            fontconfig python3 bc cpio rsync kmod libelf-dev clang lld

      # 关键修复：手动安装最新版 repo 工具
      - name: Install Latest Repo Tool
        run: |
          mkdir -p ~/bin
          curl https://storage.googleapis.com/git-repo-downloads/repo > ~/bin/repo
          chmod a+x ~/bin/repo
          echo "$HOME/bin" >> $GITHUB_PATH  # 添加至 PATH

      # 使用清华镜像源加速下载
      - name: Clone Android Kernel (Android 12 5.10.136)
        run: |
          mkdir android-kernel && cd android-kernel
          export REPO_URL="https://mirrors.tuna.tsinghua.edu.cn/git/git-repo"
          ~/bin/repo init -u https://aosp.tuna.tsinghua.edu.cn/kernel/manifest \
            -b common-android12-5.10 --depth=1
          ~/bin/repo sync -c -j$(nproc) --no-tags --no-clone-bundle

      # 切换到精确 commit（可选）
      - name: Checkout Specific Commit
        run: |
          cd android-kernel/common
          git checkout android12-5.10.136

      - name: Configure Kernel
        run: |
          cd android-kernel/common
          make ARCH=arm64 gki_defconfig
          ./scripts/config --module CONFIG_BTRFS_FS
          ./scripts/config --disable MODULE_SIG
          make ARCH=arm64 olddefconfig

      - name: Build Btrfs Module
        run: |
          cd android-kernel/common
          make ARCH=arm64 CROSS_COMPILE=aarch64-linux-gnu- -j$(nproc) fs/btrfs/btrfs.ko

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: btrfs.ko-android12-5.10.136
          path: android-kernel/common/fs/btrfs/btrfs.ko
