name: Build Btrfs Module for Android GKI

on:
  push:
    branches: [ "main" ]  # 触发条件：main 分支 push 时运行
  workflow_dispatch:      # 允许手动触发

jobs:
  build:
    runs-on: ubuntu-latest  # 使用最新 Ubuntu 环境

    steps:
      # 1. 检出代码（如果仓库有自定义脚本）
      - name: Checkout
        uses: actions/checkout@v4

      # 2. 安装依赖（Android 内核编译所需工具）
      - name: Install Dependencies
        run: |
          sudo apt-get update -y
          sudo apt-get install -y git-core gnupg flex bison build-essential \
            zip curl zlib1g-dev gcc-multilib g++-multilib libc6-dev-i386 \
            libncurses5 lib32ncurses5-dev x11proto-core-dev libx11-dev \
            lib32z1-dev libgl1-mesa-dev libxml2-utils xsltproc unzip \
            fontconfig python3 bc cpio rsync kmod libelf-dev clang lld

      # 3. 下载 Android 5.10 内核源码
      - name: Clone Android Kernel
        run: |
          mkdir android-kernel && cd android-kernel
          repo init -u https://android.googlesource.com/kernel/manifest -b common-android-mainline
          repo sync -j$(nproc) -c --no-tags

      # 4. 配置内核（启用 Btrfs 模块）
      - name: Configure Kernel
        run: |
          cd android-kernel/common
          make ARCH=arm64 gki_defconfig
          ./scripts/config --module CONFIG_BTRFS_FS  # 启用 Btrfs 模块
          make ARCH=arm64 olddefconfig

      # 5. 编译 Btrfs 模块
      - name: Build Btrfs Module
        run: |
          cd android-kernel/common
          make ARCH=arm64 CROSS_COMPILE=aarch64-linux-gnu- -j$(nproc) fs/btrfs/btrfs.ko

      # 6. 上传编译好的模块（可在 Actions 页面下载）
      - name: Upload Artifact
        uses: actions/upload-artifact@v3
        with:
          name: btrfs.ko
          path: android-kernel/common/fs/btrfs/btrfs.ko
