name: Build Btrfs for Android 12 (5.10.136)

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-22.04
    timeout-minutes: 60

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      # 关键修改：安装完整的交叉编译工具链
      - name: Install Toolchains
        run: |
          sudo apt-get update -y
          sudo apt-get install -y \
            build-essential \
            gcc-aarch64-linux-gnu \
            binutils-aarch64-linux-gnu \
            libncurses-dev \
            flex bison libelf-dev

          # 验证工具链安装
          aarch64-linux-gnu-gcc --version
          which aarch64-linux-gnu-ld

      - name: Install Latest Repo Tool
        run: |
          mkdir -p ~/bin
          curl https://storage.googleapis.com/git-repo-downloads/repo > ~/bin/repo
          chmod a+x ~/bin/repo
          echo "$HOME/bin" >> $GITHUB_PATH

      - name: Clone Android Kernel
        run: |
          mkdir android-kernel && cd android-kernel
          export REPO_URL="https://mirrors.tuna.tsinghua.edu.cn/git/git-repo"
          ~/bin/repo init -u https://aosp.tuna.tsinghua.edu.cn/kernel/manifest \
            -b common-android12-5.10 --depth=1
          ~/bin/repo sync -c -j$(nproc) --no-tags --no-clone-bundle

      - name: Find and Checkout Correct Tag
        run: |
          cd android-kernel/common
          git fetch --tags
          SELECTED_TAG=$(git tag -l "*5.10.136*" | head -1)
          if [ -z "$SELECTED_TAG" ]; then
            git checkout common-android12-5.10
          else
            git checkout "$SELECTED_TAG"
          fi

      # 关键修改：明确指定工具链路径
      - name: Build Btrfs Module
        run: |
          cd android-kernel/common
          make ARCH=arm64 CROSS_COMPILE=aarch64-linux-gnu- \
            CC=aarch64-linux-gnu-gcc \
            LD=aarch64-linux-gnu-ld \
            -j$(nproc) fs/btrfs/btrfs.ko

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: btrfs.ko-android12-5.10.136
          path: android-kernel/common/fs/btrfs/btrfs.ko
