name: Build Btrfs for Android 12 (5.10.168_r00)

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-22.04
    timeout-minutes: 90

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Dependencies
        run: |
          sudo apt-get update -y
          
          # 移除冲突包
          sudo apt-get remove -y gcc-multilib g++-multilib || true
          
          # 安装基础工具
          sudo apt-get install -y \
            git-core gnupg flex bison build-essential \
            zip curl zlib1g-dev libc6-dev-i386 \
            libncurses5 lib32ncurses5-dev \
            x11proto-core-dev libx11-dev lib32z1-dev \
            libgl1-mesa-dev libxml2-utils xsltproc unzip \
            fontconfig python3 bc cpio rsync kmod \
            libelf-dev clang lld git-lfs
          
          # 安装ARM64工具链
          sudo apt-get install -y \
            gcc-11-aarch64-linux-gnu \
            g++-11-aarch64-linux-gnu \
            binutils-aarch64-linux-gnu \
            libc6-dev-arm64-cross
          
          # 创建符号链接
          sudo ln -sf /usr/bin/aarch64-linux-gnu-gcc-11 /usr/bin/aarch64-linux-gnu-gcc
          sudo ln -sf /usr/bin/aarch64-linux-gnu-g++-11 /usr/bin/aarch64-linux-gnu-g++
          
          # 验证
          aarch64-linux-gnu-gcc --version
          aarch64-linux-gnu-g++ --version
          which aarch64-linux-gnu-ld

      - name: Setup Repo Tool
        run: |
          mkdir -p ~/bin
          curl https://storage.googleapis.com/git-repo-downloads/repo > ~/bin/repo
          chmod a+x ~/bin/repo
          echo "$HOME/bin" >> $GITHUB_PATH

      - name: Clone Android Kernel
        run: |
          mkdir android-kernel && cd android-kernel
          export REPO_URL="https://mirrors.tuna.tsinghua.edu.cn/git/git-repo"
          ~/bin/repo init -u https://aosp.tuna.tsinghua.edu.cn/kernel/manifest \
            -b android12-5.10.168_r00 --depth=1
          ~/bin/repo sync -c -j$(nproc) --no-tags --no-clone-bundle

      - name: Configure and Build
        run: |
          cd android-kernel/common
          mkdir -p out
          
          # 配置内核
          make ARCH=arm64 O=out gki_defconfig
          ./scripts/config --file out/.config --module CONFIG_BTRFS_FS
          ./scripts/config --file out/.config --disable MODULE_SIG
          make ARCH=arm64 O=out olddefconfig
          
          # 编译模块
          make ARCH=arm64 O=out \
            CROSS_COMPILE=aarch64-linux-gnu- \
            CC=aarch64-linux-gnu-gcc \
            LD=aarch64-linux-gnu-ld \
            -j$(nproc) fs/btrfs/btrfs.ko
          
          # 验证
          modinfo out/fs/btrfs/btrfs.ko | grep vermagic

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: btrfs.ko-android12-5.10.168_r00
          path: android-kernel/common/out/fs/btrfs/btrfs.ko
